### ISSUE TITLE
Assemble Download Stats for the Woods Web Analytics Report

### ISSUE THREAD

**Issue by phargogh** [natcap/softwareteam#122]
Request from Terry:

> We are doing our annual web analytics report for Woods.  Would you please send me the number of downloads from Sept 1, 2020 - August 31, 2021.  We also need the number for Sept 1, 2019 - August 31, 2020.

**Comment by phargogh** [comment]
Hey, look at that!  Got a repo from the last time I did this: https://github.com/phargogh/invest-monthly-downloads-from-gcs-logging

**Comment by phargogh** [comment]
I'm working on a couple of scripts in that repo, but I wanted to also mention that this only reflects the download stats through our buckets and not any downloads through the github releases page.  I'd like to also include a script to retrieve and include those numbers.

**Comment by phargogh** [comment]
Actually, I take that back about github download counts.  Right now, it looks like we've mostly had single-digit downloads on most of our github release assets, and we also can't determine _when_ the download occurred so it's not immediately useful for the requested stats.

**Comment by dcdenu4** [comment]
>we've mostly had single-digit downloads on most of our github release assets

And I often grab assets from GitHub, so I'm one of the single digits!

>we also can't determine when the download occurred

That's surprising

**Comment by phargogh** [comment]
Yeah, it's kind of a weird situation for usage stats/analytics for github download assets.  Not ideal, for sure!  But I suppose we could retrieve the statistics weekly or monthly or something like that and get an idea of when downloads are happening.  Still, we don't have that many downloads.  I found someone's app online that makes the release download counts a bit more browseable: https://githubstats0.firebaseapp.com/

I'm attaching the download count CSV here for posterity: [monthly-counts.csv](https://github.com/natcap/softwareteam/files/7590932/monthly-counts.csv)

**Comment by phargogh** [comment]
Actually wait, I'll reopen the issue here in order to:

1. find a new home for this repository (maybe this repo, maybe the natcap repo)
2. make this work for the workbench as well

**Comment by phargogh** [comment]
I've updated the repository so that it's now owned by the natcap org at https://github.com/natcap/invest-monthly-downloads-from-gcs-logging.

The `Makefile` there has been updated to generate both `invest` and `invest-workbench` summary tables (see the readme)
