### ISSUE TITLE
ipbes-pollination-summary

### ISSUE THREAD

**Issue by phargogh** [natcap/softwareteam#47]
URL of the original repo: https://bitbucket.org/natcap/ipbes-pollination-summary

* Who's the repo maintainer?
    * @richpsharp 
* How much of the source tree should be migrated?
    * Another IPBES repo, depends on what we decide to do for IPBES.
* Are there issues to migrate?
    * No
* Is there a wiki to migrate?
    * No
* Should issue numbers be prefixed in the source tree?
    * No issues
* Does this repo require CI services?
    * No

**Comment by phargogh** [comment]
@richpsharp I took a backup of this repository and uploaded it to google drive if we ever need it.  Feel free to reopen this issue if there's more to do about this repo migration.

**Comment by richpsharp** [comment]
This shows as a "open" issue on my queue. So I'm reopening and closing...
